import mongoose from "mongoose";

// ─── Test Case Sub-schema ───────────────────────────────────────────────────
// Each question has multiple test cases generated by the AI.
// `hidden` test cases are NOT shown to the player (used only for judging),
// while the first 1-2 can be marked visible as "sample" cases.
const testCaseSchema = new mongoose.Schema({
  input: { type: String, required: true },          // stdin passed to the program
  expectedOutput: { type: String, required: true },  // exact expected stdout
  isHidden: { type: Boolean, default: true },         // hidden vs sample case
  weight: { type: Number, default: 1 },                // some cases can count more (e.g. edge cases)
});

const questionSchema = new mongoose.Schema(
  {
    roomId: {
      type: String, // inviteCode of the room this question belongs to
      required: true,
      index: true,
    },
    roundNumber: {
      type: Number,
      required: true,
    },

    // ── Question Content ──────────────────────────────────────────────────
    topic: {
      type: String, // e.g. "Arrays", "JavaScript", "Logic Puzzles"
      required: true,
    },
    difficulty: {
      type: String,
      enum: ["easy", "medium", "hard"],
      default: "medium",
    },
    title: {
      type: String,
      required: true,
    },
    prompt: {
      type: String, // full question description shown to the player
      required: true,
    },
    constraints: {
      type: String, // e.g. "1 <= n <= 10^5", optional
      default: "",
    },

    // ── AI-Generated Test Cases ───────────────────────────────────────────
    testCases: {
      type: [testCaseSchema],
      validate: {
        validator: (arr) => arr.length >= 2,
        message: "A question must have at least 2 test cases",
      },
    },

    // ── Metadata ───────────────────────────────────────────────────────────
    generatedBy: {
      type: String,
      enum: ["claude", "manual"],
      default: "claude",
    },
    timeLimitMs: {
      type: Number,
      default: 10000, // matches your Docker executor timeout
    },
  },
  { timestamps: true }
);
questionSchema.index({ roomId: 1, roundNumber: 1 }, { unique: true });

export const Question = mongoose.model("Question", questionSchema);